lib/todo_new_web/router.ex
defmodule TodoNewWeb.Router do
  use TodoNewWeb, :router

  import TodoNewWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TodoNewWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TodoNewWeb do
    pipe_through :browser

    get "/", PageController, :index

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoNewWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TodoNewWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  scope "/", TodoNewWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", TodoNewWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    resources "/tasks", TaskController
    patch "/tasks/:id/status", TaskController, :update_status
    get "/clear", TaskController, :clear_completed
    get "/:filter", TaskController, :index
  end

  scope "/tasks/:id", TodoNewWeb, as: :sub do
    pipe_through [:browser, :require_authenticated_user]
    get "/subtasks", TaskController, :subtasks
    get "/subtasks/new", TaskController, :new_subtask
    post "/subtasks", TaskController, :create_subtask
    get "/subtasks/:subtask_id/edit", TaskController, :edit_subtask
    put "/subtasks/:subtask_id", TaskController, :update_subtask
    get "/subtasks/:subtask_id", TaskController, :show_subtask
    delete "/subtasks/:subtask_id", TaskController, :delete_subtask
    patch "/subtasks/:subtask_id", TaskController, :update_subtask_status
  end
end

lib/todo_new_web/templates/page/index.html.heex
<section class="phx-hero">
  <%= if @current_user do %>
  <p>Welcome <%= @current_user.email %> </p>
  <p><%= link "Click here", to: Routes.task_path(@conn, :index) %> to manage your tasks in a new way</p>
  <% else %>
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix To-Do" %></h1>
  <p>New way to manage your to-do lists</p>
  <p><%= link "Register", to: Routes.user_registration_path(@conn, :new) %>/<%= link "Log in", to: Routes.user_session_path(@conn, :new) %> to get started</p>
  <% end %>
</section>

<%# <section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.6/CHANGELOG.md">v1.6 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://web.libera.chat/#elixir">#elixir on Libera Chat (IRC)</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
      <li>
        <a href="https://discord.gg/elixir">Elixir on Discord</a>
      </li>
    </ul>
  </article>
</section> %>