lib/todo_new_web/router.ex
defmodule TodoNewWeb.Router do
  use TodoNewWeb, :router

  import TodoNewWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TodoNewWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TodoNewWeb do
    pipe_through :browser

    get "/", PageController, :index

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoNewWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TodoNewWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  scope "/", TodoNewWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", TodoNewWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    resources "/tasks", TaskController
    patch "/tasks/:id/status", TaskController, :update_status
    get "/clear", TaskController, :clear_completed
    get "/:filter", TaskController, :index
  end

  scope "/tasks/:id", TodoNewWeb, as: :sub do
    pipe_through [:browser, :require_authenticated_user]
    get "/subtasks", TaskController, :subtasks
    get "/subtasks/new", TaskController, :new_subtask
    post "/subtasks", TaskController, :create_subtask
    get "/subtasks/:subtask_id/edit", TaskController, :edit_subtask
    put "/subtasks/:subtask_id", TaskController, :update_subtask
    get "/subtasks/:subtask_id", TaskController, :show_subtask
    delete "/subtasks/:subtask_id", TaskController, :delete_subtask
    patch "/subtasks/:subtask_id", TaskController, :update_subtask_status
  end
end

lib/todo_new/todo/task.ex
defmodule TodoNew.Todo.Task do
  use Ecto.Schema
  import Ecto.Changeset
  alias TodoNew.Accounts.User

  schema "tasks" do
    field :end_time, :naive_datetime, default: nil
    field :start_time, :naive_datetime, default: nil

    field :status, Ecto.Enum,
      values: [New: 0, Working: 1, Completed: 2, Deleted: 3],
      default: :New

    field :title
    field :time_taken, :naive_datetime, virtual: true

    belongs_to :user, User

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:title, :user_id, :status, :start_time, :end_time])
    |> validate_required([:title, :user_id])
  end
end

lib/todo_new_web/controllers/task_controller.ex
defmodule TodoNewWeb.TaskController do
  use TodoNewWeb, :controller

  alias TodoNew.Todo
  alias TodoNew.Todo.Task
  alias TodoNew.Todo.SubTask

  def index(conn, params) do
    user = conn.assigns[:current_user]
    tasks = Todo.list_user_tasks(user)
    render(conn, "index.html", tasks: tasks, filter: Map.get(params, "filter", "all"))
  end

  def new(conn, _params) do
    changeset = Todo.change_task(%Task{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"task" => task_params}) do
    user = conn.assigns[:current_user]

    case Todo.create_user_task(task_params, user) do
      {:ok, _task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: Routes.task_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Todo.get_task!(id)

    conn
    |> authorize_task(task)
    |> render("show.html", task: task)
  end

  def edit(conn, %{"id" => id}) do
    task = Todo.get_task!(id)
    conn = authorize_task(conn, task)
    changeset = Todo.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Todo.get_task!(id)
    conn = authorize_task(conn, task)

    case Todo.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Todo.get_task!(id)
    conn = authorize_task(conn, task)
    {:ok, _task} = Todo.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end

  def update_status(conn, %{"id" => id, "new_status" => new_status}) do
    task = Todo.get_task!(id)
    conn = authorize_task(conn, task)

    task_params =
      case task.status do
        :New ->
          if new_status == "Working" do
            %{status: "Working", start_time: Timex.now("Asia/Kolkata")}
          else
            %{}
          end

        :Working ->
          if new_status == "Completed" do
            %{status: "Completed", end_time: Timex.now("Asia/Kolkata")}
          else
            %{}
          end

        _ ->
          %{}
      end

    {:ok, _task} = Todo.update_task(task, task_params)

    conn
    |> put_flash(:info, "Task updated successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end

  def clear_completed(conn, _params) do
    user = conn.assigns[:current_user]
    Todo.clear_completed(user.id)
    index(conn, %{filter: "all"})
  end

  ########################################### Subtask functions ###########################################

  def subtasks(conn, %{"id" => task_id}) do
    task = Todo.get_task!(task_id)
    conn = authorize_task(conn, task)
    subtasks = Todo.list_subtasks(task_id)
    render(conn, "subtask.html", task_id: task_id, sub_tasks: subtasks)
  end

  def new_subtask(conn, %{"id" => task_id}) do
    task = Todo.get_task!(task_id)
    conn = authorize_task(conn, task)
    changeset = Todo.change_subtask(%SubTask{})
    render(conn, "newsubtask.html", task_id: task_id, changeset: changeset)
  end

  def create_subtask(conn, %{"id" => task_id, "sub_task" => subtask_params}) do
    task = Todo.get_task!(task_id)
    conn = authorize_task(conn, task)
    subtask_params = Map.put(subtask_params, "task_id", task_id)

    case Todo.create_subtask(subtask_params) do
      {:ok, _subtask} ->
        conn
        |> put_flash(:info, "SubTask created successfully.")
        |> redirect(to: Routes.sub_task_path(conn, :subtasks, task_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "newsubtask.html", task_id: task_id, changeset: changeset)
    end
  end

  def edit_subtask(conn, %{"id" => task_id, "subtask_id" => subtask_id}) do
    task = Todo.get_task!(task_id)
    subtask = Todo.get_subtask!(subtask_id)

    conn =
      conn
      |> authorize_task(task)
      |> authorize_subtask(task, subtask)

    changeset = Todo.change_subtask(subtask)
    render(conn, "editsubtask.html", task: task, subtask: subtask, changeset: changeset)
  end

  def update_subtask(conn, %{
        "id" => task_id,
        "subtask_id" => subtask_id,
        "sub_task" => subtask_params
      }) do
    task = Todo.get_task!(task_id)
    subtask = Todo.get_subtask!(subtask_id)

    conn
    |> authorize_task(task)
    |> authorize_subtask(task, subtask)

    case Todo.update_subtask(subtask, subtask_params) do
      {:ok, subtask} ->
        conn
        |> put_flash(:info, "SubTask updated successfully.")
        |> redirect(to: Routes.sub_task_path(conn, :show_subtask, task.id, subtask.id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "editsubtask.html", task: task, subtask: subtask, changeset: changeset)
    end
  end

  def show_subtask(conn, %{"id" => task_id, "subtask_id" => subtask_id}) do
    task = Todo.get_task!(task_id)
    subtask = Todo.get_subtask!(subtask_id)

    conn
    |> authorize_task(task)
    |> authorize_subtask(task, subtask)
    |> render("showsubtask.html", task: task, subtask: subtask)
  end

  def delete_subtask(conn, %{"id" => task_id, "subtask_id" => subtask_id}) do
    task = Todo.get_task!(task_id)
    subtask = Todo.get_subtask!(subtask_id)
    conn =
      conn
      |> authorize_task(task)
      |> authorize_subtask(task, subtask)
    {:ok, _subtask} = Todo.delete_subtask(subtask)
    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.sub_task_path(conn, :subtasks, task_id))
  end

  def update_subtask_status(conn, %{"id" => task_id, "subtask_id" => subtask_id, "new_status" => new_status}) do
    task = Todo.get_task!(task_id)
    subtask = Todo.get_subtask!(subtask_id)
    conn =
      conn
      |> authorize_task(task)
      |> authorize_subtask(task, subtask)

    subtask_params =
      case subtask.status do
        :New ->
          if new_status == "Working" do
            %{status: "Working", start_time: Timex.now("Asia/Kolkata")}
          else
            %{}
          end

        :Working ->
          if new_status == "Completed" do
            %{status: "Completed", end_time: Timex.now("Asia/Kolkata")}
          else
            %{}
          end

        _ ->
          %{}
      end

    {:ok, _task} = Todo.update_subtask(subtask, subtask_params)

    conn
    |> put_flash(:info, "SubTask updated successfully.")
    |> redirect(to: Routes.sub_task_path(conn, :subtasks, task_id))
  end
  def authorize_task(conn, task) do
    if task.user_id == conn.assigns[:current_user].id do
      conn
    else
      conn
      |> put_flash(:error, "Access denied")
      |> redirect(to: Routes.task_path(conn, :index))
      |> halt()
    end
  end

  def authorize_subtask(conn, task, subtask) do
    if task.id == subtask.task_id do
      conn
    else
      conn
      |> put_flash(:error, "Access denied")
      |> redirect(to: Routes.task_path(conn, :index))
      |> halt()
    end
  end
end

lib/todo_new_web/views/task_view.ex
defmodule TodoNewWeb.TaskView do
  use TodoNewWeb, :view

  def time_spent(start_time, end_time) do
    diff = Timex.diff(end_time, start_time, :seconds)
    hours = div(diff, 3600)
    minutes = div(diff - 3600 * hours, 60)
    seconds = diff - 3600 * hours - 60 * minutes
    to_string(hours) <> "h " <> to_string(minutes) <> "m " <> to_string(seconds) <> "s"
  end

  def filter(tasks, str) do
    case str do
      "all" -> tasks
      "new" -> Enum.filter(tasks, fn t -> t.status == :New end)
      "working" -> Enum.filter(tasks, fn t -> t.status == :Working end)
      "completed" -> Enum.filter(tasks, fn t -> t.status == :Completed end)
      _ -> tasks
    end
  end

  def selected(filter, str) do
    case filter == str do
      true -> "selected"
      false -> ""
    end
  end
end

lib/todo_new_web/templates/task/edit.html.heex
<h1>Edit Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/todo_new_web/templates/task/editsubtask.html.heex
<h1>Edit Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.sub_task_path(@conn, :update_subtask, @task.id,@subtask.id)) %>

<span><%= link "Back", to: Routes.sub_task_path(@conn, :subtasks, @task.id) %></span>

lib/todo_new_web/templates/task/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>
  
  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/todo_new_web/templates/task/index.html.heex
<h1>Your Tasks</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtasks</th>
      <th>Status</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Time taken</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
<%= for task <- filter(@tasks, @filter) do %>
    <tr>
      <td><%= task.title %></td>
      <td>
        <span><%= link "SubTasks", to: Routes.sub_task_path(@conn, :subtasks, task.id) %></span>
      </td>
      <td><%= task.status %></td>
      <%= if task.start_time do %>
        <td><%= Timex.format!(task.start_time,"%d-%m-%Y %H:%M:%S", :strftime)  %> </td>
      <% else %>
        <td>
        <%= link "Start working!", to: Routes.task_path(@conn, :update_status, task.id, new_status: :Working), method: :patch %>
         </td> 
      <% end %>

      <%= case task.status do %>
        <% :Completed-> %>
          <td><%= Timex.format!(task.end_time,"%d-%m-%Y %H:%M:%S", :strftime) %> </td>
        <% :Working -> %>
        <td> <%= link "Mark Done!", to: Routes.task_path(@conn, :update_status, task.id, new_status: :Completed), method: :patch %> </td>
        <% _ -> %>
        <td> </td>
      <% end %>
      <td><%= task.end_time && time_spent(task.start_time, task.end_time) %> </td>

      <td>
        <span><%= link "Edit", to: Routes.task_path(@conn, :edit, task) %></span>
        <span><%= link "Delete", to: Routes.task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= if Enum.count(filter(@tasks, "all")) > 0 do  %>
<footer class="footer" style="display: block;">
  <span class="todo-count"><strong>Total tasks[<%= Enum.count(filter(@tasks, "all")) %>]</strong></span>
  <ul class="filters">
    <li>
      <a href="/tasks" class= {selected(@filter, "all")} >All</a>
    </li>
    <li>
      <a href="/new" class= {selected(@filter, "new")} >New [<%= Enum.count(filter(@tasks, "new")) %>]</a>
    </li>
    <li>
      <a href="/working" class= {selected(@filter, "working")} >Working [<%= Enum.count(filter(@tasks, "working")) %>]</a>
    </li>
    <li>
      <a href="/completed" class= {selected(@filter, "completed")} >Completed [<%= Enum.count(filter(@tasks, "completed")) %>]</a>
    </li>
    <li>
      <a href="/clear" class= "clear-completed" >Delete Completed </a>
    </li>
  </ul>
</footer>
<% end %>
<br>
<br>
<span><%= link "Add New Task", to: Routes.task_path(@conn, :new) %></span><br><br>
<span><%= link "Task Dashboard", to: "/tasks" %></span> |
<span><%= link "Home", to: "/" %> </span>
<br><br><br>

lib/todo_new_web/templates/task/new.html.heex
<h1>New Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/todo_new_web/templates/task/newsubtask.html.heex
<h1>New Sub-Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.sub_task_path(@conn, :create_subtask, @task_id)) %>

<span><%= link "Back", to: Routes.sub_task_path(@conn, :subtasks, @task_id) %></span>

lib/todo_new_web/templates/task/show.html.heex
<h1>Show Task</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @task.title %>
  </li>

  <li>
    <strong>User:</strong>
    <%= @task.user_id %>
  </li>

  <li>
    <strong>Status:</strong>
    <%= @task.status %>
  </li>

  <li>
    <strong>Start time:</strong>
    <%= @task.start_time %>
  </li>

  <li>
    <strong>End time:</strong>
    <%= @task.end_time %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.task_path(@conn, :edit, @task) %></span> |
<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/todo_new_web/templates/task/showsubtask.html.heex
<h1>Show SubTask</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @subtask.title %>
  </li>

  <li>
    <strong>User:</strong>
    <%= @subtask.task_id %>
  </li>

  <li>
    <strong>Status:</strong>
    <%= @subtask.status %>
  </li>

  <li>
    <strong>Start time:</strong>
    <%= @subtask.start_time %>
  </li>

  <li>
    <strong>End time:</strong>
    <%= @subtask.end_time %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.sub_task_path(@conn, :edit_subtask, @task.id, @subtask.id) %></span>
<span><%= link "Back", to: Routes.sub_task_path(@conn, :subtasks, @task.id) %></span>

lib/todo_new_web/templates/task/subtask.html.heex
<h1>Task</h1> 
<h2>Sub Tasks</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Time taken</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for subtask <- @sub_tasks do %>
    <tr>
      <td><%= subtask.title %></td>
      <td><%= subtask.status %></td>
      <%= if subtask.start_time do %>
        <td><%= Timex.format!(subtask.start_time,"%d-%m-%Y %H:%M:%S", :strftime)  %> </td>
      <% else %>
        <td>
        <%= link "Start working!", to: Routes.sub_task_path(@conn, :update_subtask_status, subtask.task_id, subtask.id, new_status: :Working), method: :patch %>
         <%# <a href={ Routes.update_status_path(@conn, :update_status, task.id, %{status: "Completed"}) } > Start working!</a> %>
         </td> 
      <% end %>

      <%= case subtask.status do %>
        <% :Completed-> %>
          <td><%= Timex.format!(subtask.end_time,"%d-%m-%Y %H:%M:%S", :strftime) %> </td>
        <% :Working -> %>
        <td> <%= link "Mark Done!", to: Routes.sub_task_path(@conn, :update_subtask_status, subtask.task_id, subtask.id, new_status: :Completed), method: :patch %> </td>
        <% _ -> %>
        <td> </td>
      <% end %>
      <td><%= subtask.end_time && time_spent(subtask.start_time, subtask.end_time) %> </td>

      <td>
        <span><%= link "Edit", to: Routes.sub_task_path(@conn, :edit_subtask, @task_id, subtask.id) %></span>
        <span><%= link "Delete", to: Routes.sub_task_path(@conn, :delete_subtask, @task_id, subtask.id), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "Add New Sub Task", to: Routes.sub_task_path(@conn, :new_subtask, @task_id) %></span><br><br>
<span><%= link "Task Dashboard", to: "/tasks" %></span> |
<span><%= link "Home", to: "/" %> </span>
<br><br><br>